### ISSUE TITLE
output of pychimera --gui

### ISSUE THREAD

**Issue by UnixJunkie** [insilichem/pychimera#12]
```
# pip install pychimera
Collecting pychimera
Installing collected packages: pychimera
Successfully installed pychimera-0.2.6
# pychimera --gui
Traceback (most recent call last):
  File "/home/berenger/.local/bin/pychimera", line 11, in <module>
    import pychimera.__main__
ImportError: No module named pychimera.__main__
# python --version
Python 2.7.15rc1
```

**Comment by jaimergp** [comment]
Hi!

Thanks for the report! I cannot reproduce in my system (Arch Linux + conda), so we'll try to guess what is happening here. For some reason the executable script cannot locate the `pychimera` package, so it might be a misconfigured environment.

I would need:

- Which OS you are using. `cat /etc/issue` is enough.
- The result of `env | sort` in your system. I am particularly concerned with `$PATH` and `$PYTHONPATH` variables. 
- The result of `pip --version`.

Also, you _might_ be able to use `python -m pychimera` instead of `pychimera`, but we should resolve the other issue first.

Thanks,
Jaime.

**Comment by UnixJunkie** [comment]
```
# cat /etc/issue
Ubuntu 18.04.1 LTS
```

**Comment by UnixJunkie** [comment]
```
# pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by UnixJunkie** [comment]
```
echo $PATH
/home/myuser/.opam/4.06.1/bin:/home/myuser/.gem/ruby/2.3.0/bin:/home/myuser/bin\
:/home/myuser/bin:/home/myuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/s\
bin:/usr/bin:/sbin:/bin    
```

**Comment by UnixJunkie** [comment]
PYTHONPATH is empty. Should it be set to something?

**Comment by jaimergp** [comment]
Ok, I think I have a fresh Ubuntu VM somewhere, so I will try to reproduce the error there. I think this might be related to the pip hacks Ubuntu uses for user installations. The environment variables look OK.
Did you manage to run `python -m pychimera`? Also, it would be very useful if you could run this Python call:

```
python -c "import pychimera, sys; sys.stdout.write(str(pychimera.__path__)+'\n')"
```

I'll keep you up to date.

**Comment by jaimergp** [comment]
I have managed to reproduce your error: `pychimera` works, but `pychimera --gui` does not. A fix should be available soon... I hope :)

**Comment by jaimergp** [comment]
Ok, I think this will fix it.

Tests are passing in my local installation; let's see how it goes at Travis.

Please let me know if it works for you. You will have to install it from source like this:

```
pip uninstall pychimera
pip install https://github.com/insilichem/pychimera/archive/master.zip
```

**Comment by UnixJunkie** [comment]
Thanks a lot, amazing time to a working fix and excellent user support.
Now, pychimera --gui works!

**Comment by jaimergp** [comment]
Glad you got it working! I will cut a new release (`v0.2.7`, I think) after confirming this also works in other systems.

Thanks again for the report and patience to test it!
